from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class InfoEntry:
    title: str
    meaning: str
    formula: str | None = None
    importance: str | None = None
    interpretation: str | None = None
    watch_out: str | None = None
    history: str | None = None
    data_basis: str | None = None
    methodology_note: str | None = None


def _entry(title: str, meaning: str, **kwargs) -> InfoEntry:
    return InfoEntry(title=title, meaning=meaning, **kwargs)


INFO_CATALOG: dict[str, InfoEntry] = {
    "status_financial_data": _entry("Finanzdaten", "Zeigt, ob die freigegebenen Finanzdaten für die Analyse nutzbar sind.", watch_out="Prüfung erforderlich bedeutet meist: Quelle vorhanden, aber einzelne Feldbedeutungen müssen noch bestätigt werden.", data_basis="Workflow-Status aus Preferred Data."),
    "status_history": _entry("Historie", "Zeigt, ob historische Reihen aus der Calculation Engine aufgebaut werden konnten.", history="Die App nutzt verfügbare Geschäftsjahre; fehlende Jahre werden nicht als 0 ergänzt.", data_basis="Historical Analysis Engine V1."),
    "status_market": _entry("Marktdaten", "Zeigt, ob Kurs, Aktienzahl, Marktkapitalisierung und ggf. Unternehmenswert vorliegen.", watch_out="Der Unternehmenswert benötigt zusätzlich eine berechenbare Nettoverschuldung.", data_basis="Market Data V1."),
    "status_assumptions": _entry("Bewertungsannahmen", "Zeigt, ob die Annahmen für die Bewertung noch geprüft oder freigegeben werden müssen.", data_basis="Valuation Assumption Engine V1."),
    "status_valuation": _entry("Bewertung", "Zeigt, ob eine Bewertungsvorschau oder eine endgültig freigegebene Bewertung vorliegt.", watch_out="Eine Vorschau ist keine finale Freigabe.", data_basis="Valuation Engine V1."),
    "revenue": _entry("Umsatz", "Der Umsatz zeigt die Erlöse des Unternehmens im Geschäftsjahr.", importance="Er ist die Ausgangsbasis für Wachstum, Margen und viele Bewertungsannahmen.", history="Wichtiger als ein Einzeljahr ist die Entwicklung über mehrere Jahre.", data_basis="Freigegebene Finanzdaten der Analyse."),
    "gross_profit": _entry("Bruttoergebnis", "Das Bruttoergebnis zeigt, was nach direkten Umsatzkosten übrig bleibt.", formula="Umsatz minus direkte Umsatzkosten, soweit separat verfügbar.", importance="Es hilft, Preissetzungsmacht und Kostenstruktur zu verstehen.", data_basis="Freigegebene Finanzdaten der Analyse."),
    "operating_income": _entry("Betriebsergebnis", "Das Betriebsergebnis zeigt den operativen Gewinn vor Finanzierung und Steuern.", importance="Es ist eine zentrale Größe für operative Ertragskraft und EV/EBIT.", data_basis="Freigegebene Finanzdaten der Analyse."),
    "net_income": _entry("Jahresüberschuss", "Der Jahresüberschuss zeigt den Gewinn nach Steuern und sonstigen Ergebnisbestandteilen.", watch_out="Einmalige Effekte, Steuern und Finanzierung können ein Jahr stark verzerren.", data_basis="Freigegebene Finanzdaten der Analyse."),
    "cash_and_equivalents": _entry("Liquide Mittel", "Liquide Mittel zeigen verfügbare Zahlungsmittel und Zahlungsmitteläquivalente.", importance="Sie sind wichtig für Liquidität, Nettoverschuldung und Unternehmenswert.", data_basis="Freigegebene Bilanzdaten."),
    "accounts_receivable": _entry("Forderungen", "Forderungen zeigen noch nicht bezahlte Umsätze gegenüber Kunden.", watch_out="Stark steigende Forderungen können auf längere Zahlungsziele oder Einzugsrisiken hindeuten.", data_basis="Freigegebene Bilanzdaten."),
    "inventory": _entry("Vorräte", "Vorräte zeigen gebundenes Kapital in Waren, Material oder Produktion.", watch_out="Nicht jedes Unternehmen berichtet Vorräte separat; fehlende Vorräte werden nicht als 0 behandelt.", data_basis="Freigegebene Bilanzdaten."),
    "ppe_net": _entry("Sachanlagen", "Sachanlagen zeigen gebundenes Kapital in Grundstücken, Gebäuden, Maschinen und Anlagen.", watch_out="Separat berichtete Nutzungsrechte aus Leasing sollen nicht still mit operativem PP&E vermischt werden.", data_basis="Freigegebene Bilanzdaten mit Semantic-Gate-Policy."),
    "goodwill": _entry("Goodwill", "Goodwill entsteht typischerweise aus Übernahmen.", watch_out="Hoher Goodwill kann bei schwächerer Geschäftsentwicklung zu Abschreibungsrisiken führen.", data_basis="Freigegebene Bilanzdaten, falls verfügbar."),
    "current_assets": _entry("Umlaufvermögen", "Das Umlaufvermögen enthält kurzfristig realisierbare Vermögenswerte.", interpretation="Mehr Umlaufvermögen kann Flexibilität geben, bindet aber auch Kapital.", data_basis="Freigegebene Bilanzdaten."),
    "total_assets": _entry("Gesamtvermögen", "Das Gesamtvermögen zeigt die gesamte bilanzielle Vermögensbasis.", data_basis="Freigegebene Bilanzdaten."),
    "shareholders_equity": _entry("Eigenkapital", "Eigenkapital ist der bilanzielle Kapitalanteil der Eigentümer.", importance="Es ist Basis für Eigenkapitalquote und Eigenkapitalrendite.", data_basis="Freigegebene Bilanzdaten."),
    "current_liabilities": _entry("Kurzfristige Verbindlichkeiten", "Kurzfristige Verbindlichkeiten sind Verpflichtungen mit kurzer Fälligkeit.", data_basis="Freigegebene Bilanzdaten."),
    "accounts_payable": _entry("Verbindlichkeiten aus Lieferungen und Leistungen", "Diese Verbindlichkeiten zeigen offene Lieferantenrechnungen.", data_basis="Freigegebene Bilanzdaten."),
    "short_term_debt": _entry("Kurzfristige Finanzschulden", "Kurzfristige Finanzschulden sind zinstragende Schulden mit Fälligkeit innerhalb von zwölf Monaten.", watch_out="Lieferantenverbindlichkeiten und Leasingverbindlichkeiten dürfen nicht still einbezogen werden. Deshalb kann eine semantische Prüfung erforderlich sein.", data_basis="Freigegebene Finanzdaten nach Semantic-Gate-Policy."),
    "long_term_debt": _entry("Langfristige Finanzschulden", "Langfristige Finanzschulden zeigen zinstragende Verpflichtungen mit längerer Fälligkeit.", data_basis="Freigegebene Bilanzdaten."),
    "total_liabilities": _entry("Gesamtverbindlichkeiten", "Gesamtverbindlichkeiten zeigen alle bilanziellen Verpflichtungen.", data_basis="Freigegebene Bilanzdaten."),
    "operating_cash_flow": _entry("Operativer Cashflow", "Der operative Cashflow zeigt die Zahlungsmittel aus dem laufenden Geschäft.", importance="Er zeigt, ob Gewinne auch in Cash umgewandelt werden.", data_basis="Freigegebene Cashflow-Daten."),
    "capital_expenditures": _entry("Sachinvestitionen", "Sachinvestitionen zeigen Auszahlungen für Sachanlagen.", watch_out="Wachstum ist oft mit Investitionen verbunden; hohe Investitionen sind nicht automatisch schlecht.", data_basis="Freigegebene Cashflow-Daten."),
    "free_cash_flow": _entry("Freier Cashflow", "Der freie Cashflow zeigt, was nach operativem Cashflow und Sachinvestitionen übrig bleibt.", formula="Operativer Cashflow - Sachinvestitionen", importance="Er ist zentrale Grundlage für die Equity-DCF-Bewertung.", data_basis="Calculation Engine V1."),
    "depreciation_amortization": _entry("Abschreibungen und Amortisation", "Diese Größe umfasst Abschreibungen auf Sachanlagen plus Amortisation immaterieller Vermögenswerte.", watch_out="Unspezifische Sammelzeilen werden nicht automatisch akzeptiert.", data_basis="Freigegebene Finanzdaten nach Semantic-Gate-Policy."),
    "dividends_paid": _entry("Dividendenzahlungen", "Dividendenzahlungen zeigen tatsächlich gezahlte Ausschüttungen.", watch_out="Ausschüttungen sollten langfristig aus Gewinn oder freiem Cashflow tragbar sein.", data_basis="Freigegebene Cashflow-Daten, falls verfügbar."),
    "gross_margin": _entry("Bruttomarge", "Die Bruttomarge zeigt, welcher Anteil des Umsatzes nach direkten Kosten bleibt.", formula="Bruttoergebnis / Umsatz", interpretation="Hohe und stabile Werte können auf Preissetzungsmacht oder effiziente Leistungserbringung hindeuten.", data_basis="Calculation Engine V1."),
    "operating_margin": _entry("Operative Marge", "Die operative Marge zeigt den operativen Gewinn je Umsatz.", formula="Betriebsergebnis / Umsatz", importance="Sie ist ein Kernsignal für operative Qualität.", data_basis="Calculation Engine V1."),
    "net_margin": _entry("Nettomarge", "Die Nettomarge zeigt, wie viel Gewinn je Umsatz nach allen Aufwendungen bleibt.", formula="Jahresüberschuss / Umsatz", watch_out="Steuern, Finanzierung und Sondereffekte können sie verzerren.", data_basis="Calculation Engine V1."),
    "ebitda": _entry("EBITDA", "EBITDA ist eine interne operative Ergebnisgröße vor Abschreibungen und Amortisation.", formula="Betriebsergebnis + Abschreibungen und Amortisation", watch_out="EBITDA ersetzt nicht die Betrachtung von Investitionen und freiem Cashflow.", data_basis="Calculation Engine V1; kein Provider-EBITDA."),
    "ebitda_margin": _entry("EBITDA-Marge", "Die EBITDA-Marge zeigt EBITDA im Verhältnis zum Umsatz.", formula="EBITDA / Umsatz", watch_out="Bei kapitalintensiven Unternehmen immer zusammen mit Capex und FCF lesen.", data_basis="Calculation Engine V1."),
    "return_on_equity": _entry("Eigenkapitalrendite", "Die Eigenkapitalrendite zeigt, wie viel Gewinn im Verhältnis zum Eigenkapital erzielt wird.", formula="Jahresüberschuss / Eigenkapital", watch_out="Hohe Verschuldung oder niedriges Eigenkapital kann die Kennzahl stark erhöhen.", history="Über mehrere Jahre betrachten, nicht nur ein einzelnes Jahr.", data_basis="Calculation Engine V1."),
    "return_on_assets": _entry("Vermögensrendite", "Die Vermögensrendite zeigt, wie effizient das Vermögen Gewinn erwirtschaftet.", formula="Jahresüberschuss / Gesamtvermögen", watch_out="Asset-light und asset-heavy Unternehmen sind nur eingeschränkt vergleichbar.", data_basis="Calculation Engine V1."),
    "operating_cash_flow_margin": _entry("Operative Cashflow-Marge", "Diese Marge zeigt operativen Cashflow im Verhältnis zum Umsatz.", formula="Operativer Cashflow / Umsatz", data_basis="Calculation Engine V1."),
    "free_cash_flow_margin": _entry("FCF-Marge", "Die FCF-Marge zeigt freien Cashflow im Verhältnis zum Umsatz.", formula="Freier Cashflow / Umsatz", watch_out="Investitionszyklen können einzelne Jahre stark beeinflussen.", data_basis="Calculation Engine V1."),
    "equity_ratio": _entry("Eigenkapitalquote", "Die Eigenkapitalquote zeigt den Eigenkapitalanteil am Gesamtvermögen.", formula="Eigenkapital / Gesamtvermögen", interpretation="Eine höhere Quote kann Stabilität erhöhen; branchenspezifische Unterschiede sind wichtig.", methodology_note="Excel-/Buchvorlage nutzt Orientierungswerte als Faustregeln, nicht als automatische App-Wertung.", data_basis="Calculation Engine V1."),
    "cash_ratio": _entry("Liquidität 1. Grades", "Zeigt, welcher Anteil kurzfristiger Verbindlichkeiten durch liquide Mittel gedeckt ist.", formula="Liquide Mittel / kurzfristige Verbindlichkeiten", watch_out="Ein sehr hoher Wert kann auch ungenutztes Kapital bedeuten.", methodology_note="Orientierungswerte aus Excel-/Buchvorlage sind Faustregeln und fließen nicht automatisch in das Scoring ein.", data_basis="Calculation Engine V1."),
    "quick_ratio": _entry("Liquidität 2. Grades", "Zeigt kurzfristige Liquidität ohne Vorräte.", formula="Liquide Mittel + Forderungen / kurzfristige Verbindlichkeiten", data_basis="Calculation Engine V1."),
    "current_ratio": _entry("Liquidität 3. Grades", "Zeigt das Umlaufvermögen im Verhältnis zu kurzfristigen Verbindlichkeiten.", formula="Umlaufvermögen / kurzfristige Verbindlichkeiten", watch_out="Sehr hohe Werte können auf gebundenes Kapital hindeuten.", data_basis="Calculation Engine V1."),
    "debt_to_assets": _entry("Schuldenquote", "Zeigt zinstragende Schulden im Verhältnis zum Vermögen.", formula="Kurzfristige Finanzschulden + langfristige Finanzschulden / Gesamtvermögen", data_basis="Calculation Engine V1."),
    "debt_to_equity": _entry("Debt to Equity", "Zeigt zinstragende Schulden im Verhältnis zum Eigenkapital.", formula="Kurzfristige Finanzschulden + langfristige Finanzschulden / Eigenkapital", watch_out="Bei niedrigem oder negativem Eigenkapital schwer interpretierbar.", data_basis="Calculation Engine V1."),
    "net_debt": _entry("Nettoverschuldung", "Nettoverschuldung zeigt Finanzschulden nach Abzug liquider Mittel.", formula="Kurzfristige Finanzschulden + langfristige Finanzschulden - liquide Mittel", watch_out="Wenn kurzfristige Finanzschulden semantisch nicht freigegeben sind, ist Net Debt nicht vollständig berechenbar.", data_basis="Calculation Engine V1."),
    "net_debt_to_ebitda": _entry("Nettoverschuldung / EBITDA", "Zeigt, wie viele Jahre EBITDA rechnerisch zur Rückzahlung der Nettoverschuldung nötig wären.", formula="Nettoverschuldung / EBITDA", watch_out="Negative EBITDA-Werte und zyklische Gewinne erfordern besondere Vorsicht.", data_basis="Calculation Engine V1."),
    "working_capital": _entry("Nettoumlaufvermögen", "Working Capital zeigt kurzfristig gebundenes operatives Kapital.", formula="Umlaufvermögen - kurzfristige Verbindlichkeiten", data_basis="Calculation Engine V1."),
    "working_capital_to_revenue": _entry("Working Capital / Umsatz", "Zeigt, wie viel Kapital relativ zum Umsatz im Umlaufvermögen gebunden ist.", formula="Working Capital / Umsatz", watch_out="Working Capital kann bei Wachstum steigen und FCF kurzfristig belasten.", data_basis="Calculation Engine V1."),
    "receivables_days": _entry("Forderungslaufzeit", "Zeigt näherungsweise, wie lange Umsätze als Forderungen gebunden bleiben.", formula="Forderungen * 365 / Umsatz", data_basis="Calculation Engine V1."),
    "payables_days": _entry("Verbindlichkeitenlaufzeit", "Zeigt näherungsweise, wie lange Lieferantenverbindlichkeiten ausstehen.", formula="Verbindlichkeiten aus Lieferungen und Leistungen * 365 / Umsatz", data_basis="Calculation Engine V1."),
    "inventory_intensity": _entry("Vorratsintensität", "Zeigt den Anteil der Vorräte am Vermögen.", formula="Vorräte / Gesamtvermögen", watch_out="Nur sinnvoll, wenn Vorräte separat berichtet werden.", data_basis="Calculation Engine V1."),
    "inventory_days": _entry("Lagerdauer", "Zeigt näherungsweise, wie lange Vorräte gebunden sind.", formula="Vorräte * 365 / Umsatz", watch_out="Nur sinnvoll, wenn Vorräte separat berichtet werden.", data_basis="Calculation Engine V1."),
    "capex_ratio": _entry("Sachinvestitionen / operativer Cashflow", "Zeigt, welcher Anteil des operativen Cashflows in Sachanlagen reinvestiert wird.", formula="Sachinvestitionen / operativer Cashflow", interpretation="Moderate Reinvestitionen können gesund sein; sehr hohe Werte müssen im Kontext von Wachstum gelesen werden.", data_basis="Calculation Engine V1."),
    "market_cap": _entry("Marktkapitalisierung", "Die Marktkapitalisierung zeigt den Börsenwert des Eigenkapitals.", formula="Aktienkurs * Aktienanzahl, ggf. mit ADR-/ADS-Bezug.", data_basis="Market Data V1."),
    "enterprise_value": _entry("Unternehmenswert", "Der Unternehmenswert berücksichtigt Eigenkapitalwert und Nettoverschuldung.", formula="Marktkapitalisierung + Nettoverschuldung", watch_out="Wenn Net Debt noch nicht freigegeben ist, bleibt EV bewusst nicht berechenbar.", data_basis="Market Data V1 plus Calculation Engine V1."),
    "latest_fy_pe": _entry("KGV", "Das KGV zeigt den Preis je Einheit Jahresüberschuss.", formula="Marktkapitalisierung / Jahresüberschuss", watch_out="Niedrig ist nicht automatisch billig; Wachstum, Qualität und Sondereffekte zählen.", data_basis="Valuation Engine V1."),
    "latest_fy_ev_ebit": _entry("EV / EBIT", "Zeigt den Unternehmenswert je Einheit operativen Gewinn.", formula="Enterprise Value / Betriebsergebnis", importance="EV berücksichtigt auch Finanzierungsstruktur.", data_basis="Valuation Engine V1."),
    "latest_fy_ev_ebitda": _entry("EV / EBITDA", "Zeigt den Unternehmenswert je Einheit EBITDA.", formula="Enterprise Value / EBITDA", watch_out="Bei kapitalintensiven Unternehmen nicht ohne Capex betrachten.", data_basis="Valuation Engine V1."),
    "latest_fy_p_fcf": _entry("Kurs-FCF-Verhältnis", "Zeigt den Preis des Eigenkapitals relativ zum freien Cashflow.", formula="Marktkapitalisierung / freier Cashflow", data_basis="Valuation Engine V1."),
    "earnings_yield": _entry("Gewinnrendite", "Die Gewinnrendite kehrt das KGV um.", formula="Jahresüberschuss / Marktkapitalisierung", data_basis="Valuation Engine V1."),
    "fcf_yield": _entry("FCF-Rendite", "Die FCF-Rendite zeigt freien Cashflow relativ zur Marktkapitalisierung.", formula="Freier Cashflow / Marktkapitalisierung", data_basis="Valuation Engine V1."),
    "dcf": _entry("DCF-Bewertung", "Die DCF-Bewertung schätzt den Wert zukünftiger Cashflows in heutigem Geld.", importance="Sie macht Annahmen zu Cashflow, Wachstum und Rendite transparent.", watch_out="Die aktuelle App nutzt die freigegebene FCF-Basis der Frozen Valuation Engine, nicht ungeprüft die alte Excel-Owner-Earnings-Formel.", data_basis="Valuation Engine V1."),
    "base_fcf": _entry("Ausgangs-Cashflow", "Der Ausgangs-Cashflow ist die normalisierte FCF-Basis für die Bewertung.", data_basis="Valuation Assumption Engine V1."),
    "growth_rate": _entry("Wachstumsrate", "Die Wachstumsrate beschreibt, wie stark der Ausgangs-Cashflow in der Planungsphase wachsen soll.", watch_out="Hohes Wachstum ist oft mit Investitionen und Risiko verbunden.", data_basis="Valuation Assumption Engine V1."),
    "discount_rate": _entry("Diskontierungszins", "Der Diskontierungszins ist die geforderte Eigenkapitalrendite.", importance="Zukünftige Cashflows werden abgezinst, weil ein Euro heute mehr wert ist als ein unsicherer Euro in der Zukunft.", watch_out="In dieser Equity-DCF ist das Cost of Equity, nicht WACC. Ein höherer Zinssatz ist konservativer.", data_basis="Valuation Assumption Engine V1."),
    "terminal_growth_rate": _entry("Ewige Wachstumsrate", "Die ewige Wachstumsrate beschreibt das langfristige Wachstum nach der Detailphase.", watch_out="Sie muss konservativ sein und unter dem Diskontierungszins liegen.", data_basis="Valuation Assumption Engine V1."),
    "projection_years": _entry("Planungszeitraum", "Der Planungszeitraum legt fest, wie viele Jahre explizit projiziert werden.", data_basis="Valuation Assumption Engine V1."),
    "fair_value": _entry("Fairer Wert", "Der faire Wert ist der berechnete Wert je Aktie oder Anteil im Szenario.", watch_out="Er hängt direkt von den Annahmen ab und ist keine Kaufempfehlung.", data_basis="Valuation Engine V1."),
    "margin_of_safety": _entry("Sicherheitsmarge", "Die Sicherheitsmarge zeigt den Abstand zwischen fairem Wert und aktuellem Marktpreis.", formula="Abstand zwischen fairem Wert und Marktpreis nach Frozen Valuation Engine.", data_basis="Valuation Engine V1."),
    "quality_summary": _entry("Unternehmensqualität", "Die Unternehmensqualität fasst Profitabilität, Cashflow, Bilanz, Wachstum und Stabilität zusammen.", watch_out="Datenvertrauen ist getrennt von Unternehmensqualität zu lesen.", data_basis="Business Quality Engine V1."),
    "data_confidence": _entry("Datenvertrauen", "Datenvertrauen zeigt Hinweise zur Vollständigkeit und Verlässlichkeit der Datenbasis.", watch_out="Fehlende Daten sind nicht automatisch schlechte Unternehmensqualität.", data_basis="Business Quality Engine V1."),
    "latest_fy_pb": _entry("KBV", "Das Kurs-Buchwert-Verhältnis zeigt den Preis des Eigenkapitals relativ zum bilanziellen Eigenkapital.", formula="Marktkapitalisierung / Eigenkapital", watch_out="Bei negativem Eigenkapital ist die Kennzahl nicht sinnvoll interpretierbar.", data_basis="Excel-/Buch-Multiple in der Valuation-Schicht."),
    "latest_fy_p_ocf": _entry("KCV", "Das Kurs-Cashflow-Verhältnis zeigt den Preis des Eigenkapitals relativ zum operativen Cashflow.", formula="Marktkapitalisierung / operativer Cashflow", watch_out="Bei negativem oder fehlendem operativem Cashflow nicht sinnvoll interpretierbar.", data_basis="Excel-/Buch-Multiple in der Valuation-Schicht."),
    "latest_fy_ev_sales": _entry("EV / Umsatz", "EV / Umsatz setzt den Unternehmenswert ins Verhältnis zum Umsatz.", formula="Enterprise Value / Umsatz", interpretation="Höhere Werte können bei überdurchschnittlichen Margen plausibler sein, bleiben aber nur eine Orientierung.", data_basis="Excel-/Buch-Multiple in der Valuation-Schicht."),
    "latest_fy_ev_fcf": _entry("EV / FCF", "EV / FCF vergleicht den Unternehmenswert mit einem Entity-Free-Cashflow.", formula="Enterprise Value / Entity FCF nach Excel-/Buchmethode.", watch_out="Die App verwendet hierfür nicht den Equity-FCF. Wenn Zinsaufwand für Entity-FCF fehlt, bleibt die Kennzahl nicht verfügbar.", data_basis="EXCEL_BOOK_ENTITY_FCF_V1."),
    "owner_earnings": _entry("Owner Earnings", "Owner Earnings schätzen den Eigentümerertrag der Eigenkapitalgeber.", formula="Jahresüberschuss + Abschreibungen - Owner-CAPEX - Veränderung Operating Working Capital", watch_out="Fehlende immaterielle Investitionen oder Working-Capital-Bestandteile werden nicht als 0 eingesetzt.", data_basis="Excel-/Buchmethode V1."),
    "owner_earnings_capex": _entry("Owner-Earnings-CAPEX", "Investitionsbasis der Owner-Earnings-Methode.", formula="Sachinvestitionen + Käufe immaterieller Anlagewerte", watch_out="Nicht separat berichtete immaterielle Investitionen werden nicht automatisch als 0 behandelt.", data_basis="Excel-/Buchmethode V1."),
    "operating_working_capital": _entry("Operating Working Capital", "Operativ gebundenes Working Capital nach Excel-DCF-Logik.", formula="Vorräte + Forderungen aus Lieferungen und Leistungen - Verbindlichkeiten aus Lieferungen und Leistungen", watch_out="Nicht identisch mit allgemeinem Working Capital aus Umlaufvermögen minus kurzfristigen Verbindlichkeiten.", data_basis="Excel-/Buchmethode V1."),
    "change_in_operating_working_capital": _entry("Veränderung Operating Working Capital", "Zeigt die Veränderung des operativ gebundenen Working Capitals gegenüber dem Vorjahr.", formula="Operating Working Capital aktuelles Jahr - Operating Working Capital Vorjahr", watch_out="Wenn ein Jahr fehlt, wird nichts imputiert.", data_basis="Excel-/Buchmethode V1."),
    "cost_of_equity": _entry("Diskontierungsfaktor nach Excel-/Buchmethode", "Der Diskontierungszins folgt der Excel-Logik aus fairem KGV, risikofreiem Zins und Mindestverzinsung.", formula="1 / faires KGV + risikofreier Zins + Mindestaufschlag auf mindestens 7 %", watch_out="Das faire KGV muss sichtbar aus Multiplikatorenmethode oder manueller Annahme kommen.", data_basis="EXCEL_BOOK_DISCOUNT_RATE_V1."),
    "terminal_value": _entry("Ewige Rente", "Die ewige Rente schätzt den Wert nach der Detailplanungsphase.", formula="Owner Earnings letztes Planjahr * (1 + g) / (r - g)", watch_out="Die ewige Wachstumsrate muss kleiner als der Diskontierungszins sein.", data_basis="Excel-/Buchmethode V1."),
    "base_pe": _entry("Sockel-KGV", "Ausgangswert der Multiplikatorenmethode.", interpretation="Die Excel-/Buchvorlage nennt 7-8 als Orientierungsbereich.", watch_out="Orientierungswert, keine automatische Marktregel.", data_basis="Manuelle oder gespeicherte Buchannahme."),
    "financial_stability_addon": _entry("Finanzielle Stabilität", "Aufschlag für Bilanz- und Cashflow-Stabilität.", formula="Manueller KGV-Aufschlag nach Prüfung von Gearing, dynamischer Verschuldung, Eigenkapitalquote und FCF.", data_basis="Excel-/Buchmethode V1."),
    "market_position": _entry("Marktposition", "Manuelle Bewertung der Marktstellung nach Porters fünf Kräften.", formula="Punkteingaben 0-5 für Rivalität, neue Anbieter, Lieferantenmacht, Abnehmermacht und Ersatzprodukte.", watch_out="Diese Punkte werden nicht automatisch durch KI oder Kennzahlen festgelegt.", data_basis="Manuelle Buchannahmen."),
    "profitability_addon": _entry("Rentabilität", "Bewertet die Ertragskraft für die Multiplikatorenmethode.", formula="Excel-Logik: Marktpositionsaufschlag * Rentabilitätsmultiplikator.", data_basis="Excel-/Buchmethode V1."),
    "growth_addon": _entry("Wachstum", "Aufschlag für historisches und erwartetes Wachstum.", watch_out="Zweistelliges Wachstum ist besonders vorsichtig zu prüfen.", data_basis="Excel-/Buchmethode V1."),
    "individuality_addon": _entry("Individualität", "Manueller Aufschlag für besondere, gut begründete qualitative Merkmale.", watch_out="Begründung erforderlich; keine automatische KI-Wertung als Wahrheit.", data_basis="Manuelle Buchannahmen."),
    "fair_pe": _entry("Faires KGV", "Summe der Komponenten der Multiplikatorenmethode.", formula="Sockel-KGV + finanzielle Stabilität + Marktposition/Rentabilität + Wachstum + Individualität", data_basis="Excel-/Buchmethode V1."),
    "multiplicator_fair_price_per_share": _entry("Fairer Preis je Aktie nach Multiplikatorenmethode", "Berechnet den fairen Preis aus fairem KGV und prognostiziertem Gewinn je Aktie.", formula="Faires KGV * Prognose-Gewinn je Aktie", data_basis="Excel-/Buchmethode V1."),
    "summary": _entry("Zusammenfassung", "Die Zusammenfassung ordnet Chancen, offene Prüfungen, Datenunsicherheiten und Bewertungsbandbreite zusammen.", watch_out="Keine Kauf-, Halte- oder Verkaufsempfehlung.", data_basis="Alle freigegebenen Workflow-Snapshots."),
}
