from __future__ import annotations

from stock_valuation.quality.models import QualityMetricDefinition


RULE_SOURCE_SCHMIDLIN = "SCHMIDLIN"
RULE_SOURCE_PROJECT = "PROJECT_EXTENSION"
RULE_SOURCE_GENERAL = "GENERAL_FINANCIAL_ANALYSIS"


QUALITY_DEFINITIONS: tuple[QualityMetricDefinition, ...] = (
    QualityMetricDefinition(
        "gross_margin_quality",
        "Gross Margin Quality",
        "margin_quality",
        "latest gross_margin plus 3-year trend and volatility context",
        ("gross_margin",),
        "decimal_ratio",
        "Gross margin shows how much revenue remains after direct production or service costs.",
        "AVAILABLE when latest Calculation gross_margin is available; trend/volatility enrich but do not replace the measurement.",
        "Higher and stable values indicate pricing power or cost discipline.",
        "Cross-industry comparisons can be distorted by revenue recognition and outsourcing depth.",
        "Software, semiconductor, industrial, consumer, asset-light, asset-heavy.",
        "Financial companies and businesses with non-standard gross-profit presentation.",
        RULE_SOURCE_GENERAL,
        "Broad absolute bands are used only as coarse anchors; trend and volatility are evaluated separately to avoid one-year threshold dependence.",
    ),
    QualityMetricDefinition("operating_margin_quality", "Operating Margin Quality", "profitability", "latest operating_margin", ("operating_margin",), "decimal_ratio", "Operating margin measures operating profit per unit of revenue.", "AVAILABLE when latest Calculation operating_margin is available.", "Strong if positive, high and not deteriorating.", "Capitalized costs and cyclicality can distort one-year margins.", "Most non-financial operating businesses.", "Early-stage loss companies without mature economics.", RULE_SOURCE_GENERAL, "Conservative broad profitability bands; no industry-specific claim."),
    QualityMetricDefinition("net_margin_quality", "Net Margin Quality", "profitability", "latest net_margin", ("net_margin",), "decimal_ratio", "Net margin captures profit after all reported expenses.", "AVAILABLE when latest Calculation net_margin is available.", "Positive and stable margins support durable earnings quality.", "Tax, financing and one-off items can dominate.", "Most non-financial companies.", "Banks/insurers require separate method.", RULE_SOURCE_GENERAL, "Same broad profitability anchors as other margin ratios."),
    QualityMetricDefinition("ebitda_margin_quality", "EBITDA Margin Quality", "margin_quality", "latest ebitda_margin", ("ebitda_margin",), "decimal_ratio", "EBITDA margin strips D&A from operating income using internal EBITDA only.", "AVAILABLE when latest Calculation ebitda_margin is available.", "Useful for capital-intensity context when shown with capex and FCF.", "Can overstate quality for asset-heavy businesses with high reinvestment needs.", "Most non-financial operating businesses.", "Businesses where D&A is economically central and capex data is incomplete.", RULE_SOURCE_GENERAL, "Used with capex intensity to reduce standalone EBITDA bias."),
    QualityMetricDefinition("free_cash_flow_margin_quality", "Free Cash Flow Margin Quality", "cashflow_quality", "latest free_cash_flow_margin", ("free_cash_flow_margin",), "decimal_ratio", "FCF margin measures post-capex cash generation relative to revenue.", "AVAILABLE when latest Calculation free_cash_flow_margin is available.", "High positive FCF margin indicates cash-generative economics.", "Growth investment cycles can depress FCF temporarily.", "Mature asset-light and asset-heavy businesses with meaningful capex.", "Companies with structurally irregular project cash flows need review.", RULE_SOURCE_GENERAL, "Broad absolute bands plus trend/stability context."),
    QualityMetricDefinition("fcf_to_ocf_quality", "FCF / Operating Cash Flow", "cashflow_quality", "1 - capex_ratio", ("capex_ratio",), "decimal_ratio", "Shows the share of operating cash flow left after PPE capex.", "AVAILABLE when capex_ratio is available and OCF denominator was valid upstream.", "Higher values mean less OCF is consumed by capex.", "Can penalize growth investment if interpreted without context.", "Most companies with recurring capex.", "Companies with lumpy expansion projects in a short history.", RULE_SOURCE_PROJECT, "Derived from Calculation Engine capex_ratio; no provider data used."),
    QualityMetricDefinition("ocf_to_net_income_quality", "Operating Cash Flow / Net Income", "cashflow_quality", "not implemented in V1 because raw net_income and OCF are not both exposed by Calculation/Historical outputs as same-year measures", ("operating_cash_flow", "net_income"), "decimal_ratio", "Would test earnings-to-cash conversion.", "UNAVAILABLE in V1 unless upstream exposes same-year raw measures through frozen engines.", "A value above 1 can indicate conservative accruals.", "Not available from current frozen output surface without reaching around the engines.", "Most profitable non-financial companies.", "Loss years require separate interpretation.", RULE_SOURCE_GENERAL, "Documented but not scored to preserve provider independence."),
    QualityMetricDefinition("fcf_to_net_income_quality", "Free Cash Flow / Net Income", "cashflow_quality", "not implemented in V1 because raw net_income is not exposed by Calculation/Historical outputs as same-year measure", ("free_cash_flow", "net_income"), "decimal_ratio", "Would compare post-capex cash with accounting profit.", "UNAVAILABLE in V1 unless upstream exposes same-year raw measures through frozen engines.", "A durable positive ratio supports earnings quality.", "Can be distorted by investment cycles.", "Mature non-financial companies.", "Loss years and heavy investment phases.", RULE_SOURCE_GENERAL, "Documented but not scored to preserve provider independence."),
    QualityMetricDefinition("return_on_assets_quality", "Return on Assets Quality", "capital_efficiency", "latest return_on_assets", ("return_on_assets",), "decimal_ratio", "ROA measures profit relative to asset base.", "AVAILABLE when latest Calculation return_on_assets is available.", "Higher ROA indicates efficient asset use.", "Asset-light and asset-heavy businesses are not directly comparable.", "Most non-financial companies.", "Financial companies need sector-specific asset logic.", RULE_SOURCE_GENERAL, "Broad bands are only coarse anchors; asset intensity is considered separately."),
    QualityMetricDefinition("return_on_equity_quality", "Return on Equity Quality", "capital_efficiency", "latest return_on_equity", ("return_on_equity",), "decimal_ratio", "ROE measures profit relative to book equity.", "AVAILABLE when latest Calculation return_on_equity is available.", "High ROE can indicate quality, but may also reflect leverage.", "Low equity or buybacks can inflate ROE.", "Companies with positive meaningful equity.", "Negative or tiny equity base.", RULE_SOURCE_GENERAL, "Scored with leverage checks to avoid rewarding leverage alone."),
    QualityMetricDefinition("roic_quality", "ROIC Quality", "capital_efficiency", "not implemented in V1; invested capital requires a reviewed operating capital definition", ("nopat", "invested_capital"), "decimal_ratio", "ROIC would measure returns on operating invested capital.", "UNAVAILABLE in V1.", "Potentially high-value metric once invested capital is cleanly defined.", "Current data lacks tax-normalized NOPAT and reviewed invested-capital adjustments.", "Industrial and operating businesses after definition review.", "Not reliable without reviewed invested capital.", RULE_SOURCE_PROJECT, "Explicitly deferred; no synthetic ROIC."),
    QualityMetricDefinition("equity_ratio_quality", "Equity Ratio Quality", "balance_sheet", "latest equity_ratio", ("equity_ratio",), "decimal_ratio", "Shows book equity buffer relative to total assets.", "AVAILABLE when latest Calculation equity_ratio is available.", "Higher buffers can improve resilience.", "Asset-light companies may operate with lower book equity.", "Most non-financial companies.", "Financials need regulatory capital metrics.", RULE_SOURCE_GENERAL, "Broad solvency anchor, not a standalone verdict."),
    QualityMetricDefinition("debt_to_assets_quality", "Debt to Assets Quality", "balance_sheet", "latest debt_to_assets", ("debt_to_assets",), "decimal_ratio", "Interest-bearing debt relative to assets.", "AVAILABLE when latest Calculation debt_to_assets is available.", "Lower debt burden supports resilience.", "Cash-rich companies need net-debt context.", "Most non-financial companies.", "Financial companies.", RULE_SOURCE_GENERAL, "Lower-is-better scoring with broad leverage bands."),
    QualityMetricDefinition("debt_to_equity_quality", "Debt to Equity Quality", "balance_sheet", "latest debt_to_equity", ("debt_to_equity",), "decimal_ratio", "Interest-bearing debt relative to equity.", "AVAILABLE when latest Calculation debt_to_equity is available and equity was valid upstream.", "Lower leverage is usually safer.", "Distorted by low or negative equity.", "Companies with stable positive equity.", "Negative-equity cases without manual review.", RULE_SOURCE_GENERAL, "Lower-is-better scoring; interpreted together with net debt."),
    QualityMetricDefinition("net_debt_to_ebitda_quality", "Net Debt / EBITDA Quality", "balance_sheet", "latest net_debt_to_ebitda", ("net_debt_to_ebitda",), "decimal_ratio", "Net leverage relative to internal EBITDA.", "AVAILABLE when latest Calculation net_debt_to_ebitda is available.", "Lower or negative values indicate lower financial risk.", "Negative EBITDA needs special handling upstream.", "Most non-financial operating companies.", "Loss-making companies with negative EBITDA.", RULE_SOURCE_GENERAL, "Lower-is-better scoring with conservative broad leverage bands."),
    QualityMetricDefinition("current_ratio_quality", "Current Ratio Quality", "balance_sheet", "latest current_ratio", ("current_ratio",), "decimal_ratio", "Broad short-term liquidity.", "AVAILABLE when latest Calculation current_ratio is available.", "Very low values can indicate liquidity pressure.", "High values are not always better if capital is idle.", "Most non-financial companies.", "Financials and businesses with structurally negative working capital need context.", RULE_SOURCE_GENERAL, "Liquidity bands are coarse anchors only."),
    QualityMetricDefinition("quick_ratio_quality", "Quick Ratio Quality", "balance_sheet", "latest quick_ratio", ("quick_ratio",), "decimal_ratio", "Liquidity excluding inventory.", "AVAILABLE when latest Calculation quick_ratio is available.", "Useful across inventory-light and inventory-heavy companies.", "Receivable collectability is not evaluated.", "Software, semiconductor, industrial, consumer.", "Financials.", RULE_SOURCE_GENERAL, "Preferred over inventory-heavy liquidity where inventory is irrelevant."),
    QualityMetricDefinition("cash_ratio_quality", "Cash Ratio Quality", "balance_sheet", "latest cash_ratio", ("cash_ratio",), "decimal_ratio", "Immediate cash coverage of current liabilities.", "AVAILABLE when latest Calculation cash_ratio is available.", "Higher cash coverage improves resilience.", "Excess cash can reduce returns; not a valuation signal.", "Most non-financial companies.", "Financials.", RULE_SOURCE_GENERAL, "Liquidity anchor, no market valuation inference."),
    QualityMetricDefinition("capex_intensity_quality", "Investment Intensity Quality", "cashflow_quality", "latest capex_ratio plus trend context", ("capex_ratio",), "decimal_ratio", "Shows OCF share reinvested into PPE.", "AVAILABLE when latest Calculation capex_ratio is available.", "Moderate reinvestment can be healthy; excessive capex can pressure FCF.", "Asset-heavy growth phases can be intentionally high.", "Semiconductor, industrial, consumer, asset-heavy and asset-light with context.", "Businesses with irregular project capex need longer history.", RULE_SOURCE_PROJECT, "Integrated into cashflow_quality so the score has an explicit non-zero weight."),
    QualityMetricDefinition("revenue_growth_quality", "Revenue Growth Quality", "growth", "latest revenue YoY and 3Y CAGR where available", ("revenue",), "decimal_ratio", "Measures top-line growth over time.", "AVAILABLE for YoY/3Y CAGR from Historical Analysis; insufficient longer windows are not penalized.", "Positive durable growth supports business quality.", "Growth alone is not quality without margins and cash flow.", "Most operating companies.", "Turnarounds and cyclical troughs require review.", RULE_SOURCE_GENERAL, "Trend-based scoring preferred over single-year threshold."),
    QualityMetricDefinition("earnings_growth_quality", "Earnings Growth Quality", "growth", "latest net_income YoY and 3Y CAGR where available", ("net_income",), "decimal_ratio", "Measures reported earnings growth.", "AVAILABLE when Historical net_income growth is available.", "Durable positive earnings growth supports quality.", "Negative base years are not forced into bad scores; upstream status is preserved.", "Profitable companies.", "Loss-making or turnaround companies.", RULE_SOURCE_GENERAL, "Negative-base statuses are not scored as zeros."),
    QualityMetricDefinition("fcf_growth_quality", "FCF Growth Quality", "growth", "latest free_cash_flow YoY and 3Y CAGR where available", ("free_cash_flow",), "decimal_ratio", "Measures cash generation growth.", "AVAILABLE when Historical FCF growth is available.", "Positive and stable FCF growth supports quality.", "Capex cycles can distort short windows.", "Cash-generative companies.", "Businesses with lumpy project cash flows.", RULE_SOURCE_GENERAL, "Trend-based scoring with explicit insufficient-history handling."),
    QualityMetricDefinition("margin_volatility_quality", "Margin Volatility Quality", "stability", "average of per-series population volatility for gross_margin, operating_margin, net_margin, ebitda_margin and free_cash_flow_margin", ("gross_margin", "operating_margin", "net_margin", "ebitda_margin", "free_cash_flow_margin"), "decimal_ratio", "Measures time-series stability of each margin and aggregates the available series volatilities.", "AVAILABLE when at least one margin series has two or more available annual values.", "Lower volatility indicates more stable economics.", "Three-year windows are short and can miss cycles; cross-margin level dispersion is deliberately not measured.", "Most non-financial companies.", "Highly cyclical companies need longer history.", RULE_SOURCE_PROJECT, "Volatility bands are documented and configurable; no cross-metric dispersion."),
    QualityMetricDefinition("growth_volatility_quality", "Growth Volatility Quality", "stability", "average of per-series population volatility for revenue, net_income and free_cash_flow YoY growth", ("revenue", "net_income", "free_cash_flow"), "decimal_ratio", "Measures time-series variability of each growth metric and aggregates the available series volatilities.", "AVAILABLE when at least one growth series has two or more available YoY values.", "Lower volatility indicates more predictable development.", "Short history and negative-base suppression can reduce sample size.", "Most operating companies.", "Turnarounds and cyclicals need manual context.", RULE_SOURCE_PROJECT, "Volatility thresholds are configurable; no cross-metric dispersion."),
    QualityMetricDefinition("negative_years_quality", "Negative Years Quality", "stability", "negative_years from Historical Analysis stability profile", ("revenue", "net_income", "free_cash_flow"), "count", "Counts negative reported years in relevant series.", "AVAILABLE when Historical Analysis emits negative_years.", "Fewer negative years means more stable economics.", "Negative FCF during investment phases is not automatically fatal.", "Most mature companies.", "Early-stage loss companies.", RULE_SOURCE_PROJECT, "Count-based, no zero imputation."),
    QualityMetricDefinition("missing_years_quality", "Missing Years Data Confidence", "data_confidence", "missing_years from Historical Analysis stability profile", ("revenue", "net_income", "free_cash_flow"), "count", "Counts missing/unavailable years in the historical window.", "AVAILABLE when Historical Analysis emits missing_years; informative only and not scored.", "Fewer missing years improves confidence in the data, not the business quality score.", "Only measures data completeness, not business quality directly.", "All companies.", "None; missing data is not treated as bad business economics.", RULE_SOURCE_PROJECT, "Data-confidence signal only; excluded from Business Quality Score."),
    QualityMetricDefinition("inventory_applicability_quality", "Inventory Applicability", "working_capital", "inventory_intensity/inventory_days availability status", ("inventory_intensity", "inventory_days"), "status", "Separates business-model irrelevance from poor quality.", "NOT_APPLICABLE if upstream says NOT_SEPARATELY_REPORTED; otherwise AVAILABLE/UNAVAILABLE according to Calculation status.", "Prevents asset-light companies from being penalized for no separate inventory.", "Does not judge supply-chain quality without inventory data.", "Software and other asset-light companies; also inventory-heavy companies if reported.", "None; status-only rule.", RULE_SOURCE_PROJECT, "No score penalty for not applicable conditional inventory."),
)

QUALITY_DEFINITION_BY_ID = {definition.metric_id: definition for definition in QUALITY_DEFINITIONS}
